DROP TABLE IF EXISTS users, categories, locations, events, requests, compilations, compilation_events;

CREATE TABLE IF NOT EXISTS users (
        user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_name VARCHAR(250) NOT NULL,
        user_email VARCHAR(254) NOT NULL UNIQUE
        );

CREATE TABLE IF NOT EXISTS categories (
        category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category_name VARCHAR(50) NOT NULL UNIQUE
        );

CREATE TABLE IF NOT EXISTS locations (
        location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        location_lat FLOAT NOT NULL,
        location_lon FLOAT NOT NULL,
        CONSTRAINT location_unique_values UNIQUE (location_lat, location_lon)
        );

CREATE TABLE IF EXISTS events (
        event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_annotation VARCHAR(2000) NOT NULL,
        event_category_id BIGINT NOT NULL REFERENCES categories(category_id) ON DELETE RESTRICT,
        event_confirmed_requests BIGINT NOT NULL,
        event_created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        event_description VARCHAR(7000) NOT NULL,
        event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        event_initiator_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
        event_location_id BIGINT NOT NULL REFERENCES locations(location_id) ON DELETE CASCADE,
        event_paid BOOLEAN NOT NULL,
        event_participant_limit BIGINT NOT NULL,
        event_published_on TIMESTAMP WITHOUT TIME ZONE,
        event_request_moderation BOOLEAN NOT NULL,
        event_state_action VARCHAR NOT NULL,
        event_title VARCHAR(120) NOT NULL,
        event_views BIGINT NOT NULL
        );

CREATE TABLE IF EXISTS requests (
        request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        request_created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        request_event_id BIGINT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
        request_requester_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
        request_status VARCHAR NOT NULL
        );

CREATE TABLE IF EXISTS compilations (
        compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        compilation_pinned BOOLEAN NOT NULL,
        compilation_title VARCHAR(50) NOT NULL
        );

CREATE TABLE IF EXISTS compilation_events (
        compilation_id BIGINT REFERENCES compilations (compilation_id) ON DELETE CASCADE,
        event_id BIGINT REFERENCES events (event_id) ON DELETE CASCADE,
        CONSTRAINT compilation_events_unique_values UNIQUE (compilation_id, event_id)
        );
